### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by javafanboy** [gabfl/pg_dump-to-s3#13]
I would like to create dumps from on-premises Postgre database to S3 and having the option to directly restore them either back on premises or to an AWS Aurora or RDS Postgre server as efficiently as possible. 

1. Can the dumps in S3 I make with this project be directly restored to Aurora or RDS Postgre with its import from S3 using the aws_s3 extension i.e. is the format compatible?
2. Can I backup selected schemas or only complete full databases (I need to backup selected schemas only as I run several different things in the same database that needs to be backedup/restored individually)?
3. Is data stored temporarily on disk or is it directly streamed to S3?
4. Is multi part upload used to store data in S3?

**Comment by gabfl** [comment]
1) I don't know, I am not familiard with this extension
2) It's all schemas but you can easily update the `pg_dump` statement to make it schema specific ([see here](https://github.com/gabfl/pg_dump-to-s3/blob/main/pg_dump-to-s3.sh#L43C5-L43C12))
3) Temporarilly stored on disk in `/tmp`/
4) Not by default but you can easily update the upload command ([see here](https://github.com/gabfl/pg_dump-to-s3/blob/main/pg_dump-to-s3.sh#L46))

**Comment by javafanboy** [comment]
Thanks for the info - will check ut out!
