### ISSUE TITLE
add in crontab

### ISSUE THREAD

**Issue by c3959** [gabfl/pg_dump-to-s3#4]
when it is included within crontab:

"* 0 * ​​* * /home/pg_dump/pg_dump-to-s3/pg_dump-to-s3.sh >> /home/pg_dump/file.log"

it is not executed from line 48 of the script. since it must go up to s3.
if it runs directly on the home the script works correctly. regards

**Comment by gabfl** [comment]
Can you copy paste show the exact output?

Maybe the user that runs the cron does not have s3 credentials?

**Comment by gabfl** [comment]
Closing since I did not hear back, feel free to re-open if necessary
